apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: serverloader
  namespace: serverloader
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serverloader
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 8
          memory: 1000Mi
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Auto"
